#!/usr/bin/env bash

if [ $# -lt 2 ]
then
  echo "ERROR: Less arguments."
  echo "Usage: bomb-message <message> <webhook-URL>"
else
  JSON="'"'{"text": "'$1'"}'"'"
  JOB='* * * * * /usr/bin/curl -H "Content-type:application/json" -d '$JSON' "'$2'" >> /tmp/bombing-log'
  # echo "$JOB"
  crontab -l | { cat; echo "$JOB"; } | crontab -
  unset JSON JOB
fi

